#syntax=docker/dockerfile:1
# Build Stage
FROM node:18-slim as Build
WORKDIR /countdown-client
COPY . .

RUN npm clean-install && \
  npm run build

# Production Stage
FROM nginx:latest as Production

COPY --from=Build /countdown-client/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=Build /countdown-client/dist /usr/share/nginx/html/